services:
  mysql:
    image: mysql:8.4
    container_name: redis-demo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Root@123456
      MYSQL_DATABASE: redis_shop_demo
      MYSQL_USER: redis_demo
      MYSQL_PASSWORD: RedisDemo@123
      TZ: Asia/Ho_Chi_Minh
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+07:00
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
